/**
 * River layer — atlas-based.
 *
 * For each river hex we compute a 6-bit connection bitmask (bit d = the
 * neighbor on direction d is also water — river or lake) and draw a
 * single Sprite of the pre-rendered network shape for that bitmask
 * (viewer/art/rivers/c<bitmask>.svg). The atlas SVGs were generated by
 * scripts/gen_atlas.py with naturalistic bends; channels always reach
 * each connected edge midpoint at the same width and color so neighbor
 * hexes' channels meet seamlessly.
 *
 * Z-order: above terrain, below roads.
 */

import { Container, Sprite } from 'pixi.js';
import { HEX_DIRECTIONS, hexAdd, type Hex } from '../../src/sim/world/hex.js';
import type { HexGrid } from '../../src/sim/world/grid.js';
import { hexToPixel } from './coords.js';
import type { ArtRegistry } from '../art/index.js';

const SQRT3 = Math.sqrt(3);

export interface RiverLayer {
  readonly container: Container;
}

export const createRiverLayer = (
  grid: HexGrid,
  hexSize: number,
  art: ArtRegistry,
): RiverLayer => {
  const container = new Container();
  container.label = 'rivers';
  container.eventMode = 'none';
  const spriteW = SQRT3 * hexSize;
  const spriteH = 2 * hexSize;

  for (const [h, tile] of grid.tiles()) {
    if (tile.terrain !== 'river') continue;
    let bitmask = 0;
    for (let d = 0; d < 6; d++) {
      const dir = HEX_DIRECTIONS[d] as Hex;
      const n = grid.get(hexAdd(h, dir));
      if (n === undefined) continue;
      if (n.terrain === 'river' || n.terrain === 'lake') bitmask |= 1 << d;
    }
    if (bitmask === 0) continue; // isolated river hex — no channel to draw
    const px = hexToPixel(h, hexSize);
    const sprite = new Sprite(art.river(bitmask));
    sprite.anchor.set(0.5, 0.5);
    sprite.width = spriteW;
    sprite.height = spriteH;
    sprite.position.set(px.x, px.y);
    container.addChild(sprite);
  }

  return { container };
};
